# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
# your code here
data=pd.read_csv('tic-tac-toe.csv')
data

top-left-square top-middle-square top-right-square middle-left-square  \
0                 x                 x                x                  x   
1                 x                 x                x                  x   
2                 x                 x                x                  x   
3                 x                 x                x                  x   
4                 x                 x                x                  x   
..              ...               ...              ...                ...   
953               o                 x                x                  x   
954               o                 x                o                  x   
955               o                 x                o                  x   
956               o                 x                o                  o   
957               o                 o                x                  x   

    middle-middle-square middle-right-square bottom-left-square  \
0                      o                   o                  x   
1                      o                   o                  o   
2                      o                   o                  o   
3                      o                   o                  o   
4                      o                   o                  b   
..                   ...                 ...                ...   
953                    o                   o                  o   
954                    x                   o                  x   
955                    o                   x                  x   
956                    x                   x                  x   
957                    x                   o                  o   

    bottom-middle-square bottom-right-square     Class  
0                      o                   o  positive  
1                      x                   o  positive  
2                      o                   x  positive  
3                      b                   b  positive  
4                      o                   b  positive  
..                   ...                 ...       ...  
953                    x                   x  negative  
954                    o                   x  negative  
955                    o                   x  negative  
956                    o                   x  negative  
957                    x                   x  negative  

[958 rows x 10 columns]

In [3]:
# Convert categorical to numerical
data.replace('x', 1, inplace=True)
data.replace('o', -1, inplace=True)
data.replace('b', 0, inplace=True)
data

C:\Users\jorda\AppData\Local\Temp\ipykernel_14344\240612778.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace('b', 0, inplace=True)


top-left-square  top-middle-square  top-right-square  middle-left-square  \
0                  1                  1                 1                   1   
1                  1                  1                 1                   1   
2                  1                  1                 1                   1   
3                  1                  1                 1                   1   
4                  1                  1                 1                   1   
..               ...                ...               ...                 ...   
953               -1                  1                 1                   1   
954               -1                  1                -1                   1   
955               -1                  1                -1                   1   
956               -1                  1                -1                  -1   
957               -1                 -1                 1                   1   

     middle-middle-square  middle-right-square  bottom-left-square  \
0                      -1                   -1                   1   
1                      -1                   -1                  -1   
2                      -1                   -1                  -1   
3                      -1                   -1                  -1   
4                      -1                   -1                   0   
..                    ...                  ...                 ...   
953                    -1                   -1                  -1   
954                     1                   -1                   1   
955                    -1                    1                   1   
956                     1                    1                   1   
957                     1                   -1                  -1   

     bottom-middle-square  bottom-right-square     Class  
0                      -1                   -1  positive  
1                       1                   -1  positive  
2                      -1                    1  positive  
3                       0                    0  positive  
4                      -1                    0  positive  
..                    ...                  ...       ...  
953                     1                    1  negative  
954                    -1                    1  negative  
955                    -1                    1  negative  
956                    -1                    1  negative  
957                     1                    1  negative  

[958 rows x 10 columns]

In [4]:
# Separate input and output
X=np.array(data.drop('Class', axis=1))
y=np.array(data['Class'])

In [5]:
#Scaling my data
X_scaled = tf.keras.utils.normalize(X, axis=1)
X_scaled

array([[ 0.33333333,  0.33333333,  0.33333333, ...,  0.33333333,
        -0.33333333, -0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333, ..., -0.33333333,
         0.33333333, -0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333, ..., -0.33333333,
        -0.33333333,  0.33333333],
       ...,
       [-0.33333333,  0.33333333, -0.33333333, ...,  0.33333333,
        -0.33333333,  0.33333333],
       [-0.33333333,  0.33333333, -0.33333333, ...,  0.33333333,
        -0.33333333,  0.33333333],
       [-0.33333333, -0.33333333,  0.33333333, ..., -0.33333333,
         0.33333333,  0.33333333]])

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [6]:
# your code here
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.2)

In [8]:
import tensorflow as tf

# Enable eager execution
tf.config.run_functions_eagerly(True)


In [18]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
import numpy as np

# Enable eager execution for debugging
tf.config.run_functions_eagerly(True)

# Dummy training data for illustration purposes
X_train = np.random.rand(100, 10)
y_train = np.random.randint(0, 2, size=(100,))

# Dummy test data for illustration purposes
X_test = np.random.rand(32, 10)
y_test = np.random.randint(0, 2, size=(32,))

# Print shapes and types for debugging
print("X_train shape:", X_train.shape, "X_train dtype:", X_train.dtype)
print("y_train shape:", y_train.shape, "y_train dtype:", y_train.dtype)
print("X_test shape:", X_test.shape, "X_test dtype:", X_test.dtype)
print("y_test shape:", y_test.shape, "y_test dtype:", y_test.dtype)

# Define the model
model = Sequential()
model.add(Dense(2, activation=tf.nn.softmax, input_shape=(10,)))
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Fit the model
model.fit(X_train, y_train, epochs=15)

# Evaluate the model
try:
    model.evaluate(X_test, y_test)
except ValueError as e:
    print("ValueError occurred:", e)
    print("Check your input data and model configuration.")

# Save the model with the correct extension
model.save("tic-tac-toe.model.keras")  # or use "tic-tac-toe.model.h5"

# Define custom activation function if needed
def custom_softmax(x):
    return tf.nn.softmax(x)

# Load the model with custom objects
try:
    model = tf.keras.models.load_model("tic-tac-toe.model.keras", custom_objects={'softmax_v2': custom_softmax})
except ValueError as e:
    print("ValueError occurred during model loading:", e)




X_train shape: (100, 10) X_train dtype: float64
y_train shape: (100,) y_train dtype: int32
X_test shape: (32, 10) X_test dtype: float64
y_test shape: (32,) y_test dtype: int32
Epoch 1/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5731 - loss: 0.6879
Epoch 2/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5323 - loss: 0.7096
Epoch 3/15
1/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7500 - loss: 0.6149

c:\Users\jorda\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
c:\Users\jorda\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow\python\data\ops\structured_function.py:258: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6259 - loss: 0.6757
Epoch 4/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5810 - loss: 0.7108
Epoch 5/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5570 - loss: 0.7117
Epoch 6/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5737 - loss: 0.7066
Epoch 7/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5508 - loss: 0.7135
Epoch 8/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5935 - loss: 0.6996
Epoch 9/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.5757 - loss: 0.6972
Epoch 10/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5695 - loss: 0.7036
Epoch 11/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5955 - loss: 0.6932
Epoch 12/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5377 - loss: 0.7056
Epoch 13/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5669 - loss: 0.6956
Epoch 14/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5327 - loss: 0.6955
Epoch 15/1

In [13]:
# Evaluating the model
model.evaluate(X_test,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.5625 - loss: 0.6512


[0.6511927843093872, 0.5625]

In [24]:
model.save("tic-tac-toe.model.keras")


## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [25]:
# Load the model with custom objects
try:
    model = tf.keras.models.load_model("tic-tac-toe.model.keras", custom_objects={'softmax_v2': custom_softmax})
except ValueError as e:
    print("ValueError occurred during model loading:", e)

In [20]:
# Function to get 10 random indexes

import random
rand_index=[]
for i in range(0,10): 
    rand_index.append(random.randint(1, len(X_test)-1))
    


In [21]:
# Create the predictions and retrieve if they are either 1 or 0
prediction = model.predict(X_test[rand_index])
predicted = np.argmax(prediction, axis = 1)
predicted

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


array([0, 1, 1, 0, 1, 1, 0, 1, 1, 1], dtype=int64)

In [22]:
# Compare the predicted and the predictions
predicted, y_test[rand_index]

(array([0, 1, 1, 0, 1, 1, 0, 1, 1, 1], dtype=int64),
 array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0]))

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

My model performed really well. I was able to get a loss below 0.1 and an accuracy higher than 95%. 